In [1]:
# Install Sckit-learn
#!pip install -U scikit-learn
#!pip install pandas
#!pip install joblib

In [10]:
# Import essential Libraries
import numpy as np
import pandas as pd
import joblib
from joblib import dump, load

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [11]:
# create Pandas DataFrame
rentalDF = pd.read_csv('data/rental_1000.csv')

In [12]:
# Consider Features and Labels
X = rentalDF[['rooms','sqft']].values   # Features
y = rentalDF['price'].values           # Labels

In [13]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20)

In [18]:
# Training the Dataset
lr = LinearRegression()
model = lr.fit(X_train, y_train)

In [19]:
joblib.dump(model,'model/rentalprediciton.joblib')

['model/rentalprediciton.joblib']

In [20]:
model = joblib.load('model/rentalprediciton.joblib')

In [27]:
X_test[0],y_test[0]

(array([   4, 1536]), np.int64(76021))

In [29]:
model.predict(X_test[[0]])

array([78824.19850088])

In [32]:
print(f"The Actual Rental Price for Rooms= {X_test[0][0]}  and Area in Sqft=  {X_test[0][1]}  is {y_test[0]}")

The Actual Rental Price for Rooms= 4  and Area in Sqft=  1536  is 76021


In [35]:
print(f"The Predicted Rental Price for Rooms= {X_test[0][0]}  and Area in Sqft=  {X_test[0][1]}  is {model.predict(X_test[[0]])}")

The Predicted Rental Price for Rooms= 4  and Area in Sqft=  1536  is [78824.19850088]


In [21]:
# For Testing

In [22]:
# Cofficent and Intercept
cofficent = model.coef_
intercept = model.intercept_

In [24]:
model.predict(np.array([[2, 1059]]))

array([54114.923514])

In [25]:
model.predict(np.array([[2, 1500]]))

array([76036.81983785])